/*TABLA LA CUAL NOS PERMITE GUARDAR LAS DISTINTAS FECHAS DEL PRODE*/

CREATE TABLE schedures(
	id 		   int(10) auto_increment PRIMARY KEY, /*ATRIBUTO EL CUAL PERMITE IDENTIFICAR UNIVOCAMENTE UNA FECHA*/
	fixture_id int(10),							   /*ATRIBUTO EL CUAL HACE REFERENCIA A QUE FIXTURE PERTENECE LA FECHA, ES DECIR ES FOREIGN KEY DE LA TABLA FIXTURE*/
	created_at DATETIME,
	updated_at DATETIME
)ENGINE=InnoDB;
