/*TABLA TEAMS LA CUAL NOS PERMITE GUARDAR TODA LA INFORMACION DE LOS DISTINTO EQUIPOS QUE FORMAN EL PRODE*/

CREATE TABLE teams(
	id         int(11) auto_increment PRIMARY KEY, /*ATRIBUTO EL CUAL NOS PERMITE IDENTIFICAR UNIVOCAMENTE UN EQUIPO*/
	name       VARCHAR(128),
	created_at DATETIME,
	updated_at DATETIME
)ENGINE=InnoDB;
