/*TABLA USUARIO LA CUAL PERMITE GUARDAR LA INFORMACION DE CADA UNO DE LOS USUARIOS QUE JUEGAN AL PRODE*/

CREATE TABLE users (
  id         int(11) auto_increment PRIMARY KEY, /*ATRIBUTO EL CUAL PERMITE IDENTIFICAR UNIVOCAMENTE UN USUARIO*/
  username   VARCHAR(128),
  password   VARCHAR(128),
  fixture_id int(10),							 /*ATRIBUTO EL CUAL HACE REFERENCIA AL FIXTURE QUE SE SUBSCRIBIO EL USURIO, ES DECIR ES FOREIGN KEY DE LA TABLA FIXTURES*/
  created_at DATETIME,
  updated_at DATETIME
)ENGINE=InnoDB;

